// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using MyContacts.Models;
using System;

#nullable disable



namespace MyContacts.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("MyContacts.Models.Category", b =>
            {
                b.Property<int>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CategoryId");

                b.ToTable("Categories");

                b.HasData(
                    new
                    {
                        CategoryId = 1,
                        Name = "Family"
                    },
                    new
                    {
                        CategoryId = 2,
                        Name = "Friend"
                    },
                    new
                    {
                        CategoryId = 3,
                        Name = "Work"
                    });
            });

            // Other parts of the file remain unchanged

            modelBuilder.Entity("MyContacts.Models.Contact", b => {
                b.HasData(
                    new
                    {
                        ContactId = 1,
                        CategoryId = 1,
                        DateAdded = DateTime.Now,
                        Email = "sgudmestad@gmail.com",
                        FirstName = "Scott",
                        LastName = "Gudmestad",
                        PhoneNumber = "123-456-7890"
                    },
                    // Other contacts
                    new
                    {
                        ContactId = 2,
                        CategoryId = 1,
                        DateAdded = DateTime.Now,
                        Email = "ggudmestad@gmail.com",
                        FirstName = "Gerry",
                        LastName = "Gudmestad",
                        PhoneNumber = "123-456-7890"
                    },
                    new
                    {
                        ContactId = 3,
                        CategoryId = 2,
                        DateAdded = DateTime.Now,
                        Email = "bboyer@gmail.com",
                        FirstName = "Blake",
                        LastName = "Boyer",
                        PhoneNumber = "123-456-7890"
                    }
                );
            });

            // Remaining parts of the file

            
            

            modelBuilder.Entity("MyContacts.Models.Contact", b =>
            {
                b.HasOne("MyContacts.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");
            });
#pragma warning restore 612, 618
        }
    }
}
